# Generated by Django 3.1.3 on 2023-07-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230706_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='full_time',
            new_name='correct',
        ),
    ]
